# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: latex_ocr.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0flatex_ocr.proto\x12\x08latexocr\"\"\n\x0cLatexRequest\x12\x12\n\nimage_path\x18\x01 \x01(\t\"\x1b\n\nLatexReply\x12\r\n\x05latex\x18\x01 \x01(\t\"&\n\x12ServerIsReadyReply\x12\x10\n\x08is_ready\x18\x01 \x01(\x08\"1\n\x0cServerConfig\x12\x0e\n\x06\x64\x65vice\x18\x01 \x01(\t\x12\x11\n\tcache_dir\x18\x02 \x01(\t\"\x07\n\x05\x45mpty2\xbf\x01\n\x08LatexOCR\x12?\n\rGenerateLatex\x12\x16.latexocr.LatexRequest\x1a\x14.latexocr.LatexReply\"\x00\x12:\n\x07IsReady\x12\x0f.latexocr.Empty\x1a\x1c.latexocr.ServerIsReadyReply\"\x00\x12\x36\n\tGetConfig\x12\x0f.latexocr.Empty\x1a\x16.latexocr.ServerConfig\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'latex_ocr_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_LATEXREQUEST']._serialized_start=29
  _globals['_LATEXREQUEST']._serialized_end=63
  _globals['_LATEXREPLY']._serialized_start=65
  _globals['_LATEXREPLY']._serialized_end=92
  _globals['_SERVERISREADYREPLY']._serialized_start=94
  _globals['_SERVERISREADYREPLY']._serialized_end=132
  _globals['_SERVERCONFIG']._serialized_start=134
  _globals['_SERVERCONFIG']._serialized_end=183
  _globals['_EMPTY']._serialized_start=185
  _globals['_EMPTY']._serialized_end=192
  _globals['_LATEXOCR']._serialized_start=195
  _globals['_LATEXOCR']._serialized_end=386
# @@protoc_insertion_point(module_scope)
