# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: service.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rservice.proto\x12\x08latexocr\"\"\n\x0cLatexRequest\x12\x12\n\nimage_path\x18\x01 \x01(\t\"\x1b\n\nLatexReply\x12\r\n\x05latex\x18\x01 \x01(\t2K\n\x08LatexOCR\x12?\n\rGenerateLatex\x12\x16.latexocr.LatexRequest\x1a\x14.latexocr.LatexReply\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'service_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_LATEXREQUEST']._serialized_start=27
  _globals['_LATEXREQUEST']._serialized_end=61
  _globals['_LATEXREPLY']._serialized_start=63
  _globals['_LATEXREPLY']._serialized_end=90
  _globals['_LATEXOCR']._serialized_start=92
  _globals['_LATEXOCR']._serialized_end=167
# @@protoc_insertion_point(module_scope)
